export enum SECTIONS {
  LOGIN = "LOGIN",
  PERSONAL_DATA = "PERSONAL_DATA",
  ACTIVATE_ACCOUNT = "ACTIVATE_ACCOUNT",
  CHANGE_PASSWORD = "CHANGE_PASSWORD",
  SIGNUP_SUCCESS = "SIGNUP_SUCCESS",
  FORGET_PASSWORD = "FORGET_PASSWORD",
  EMAIL_SENT = "EMAIL_SENT",
  SET_UP_SUBSCRIPTION = "SET_UP_SUBSCRIPTION",
}
