version: "3.9"

services:
  praesideo-frontend:
    image: $REGISTRY/$APP:$GIT_COMMIT_SHORT
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
