export enum Exceptions {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  SIMILAR_PASSWORD = "SIMILAR_PASSWORD",
  PASSWORDS_DO_NOT_MATCH = "PASSWORDS_DO_NOT_MATCH",
  PASSWORDS_DO_NOT_MATCH_REGEX = "PASSWORDS_DO_NOT_MATCH_REGEX",
  REGISTRATION_EMAIL_EXISTS = "REGISTRATION_EMAIL_EXISTS",
  REGISTRATION_EMAIL_DOMAIN_IS_DIFFERENT = "REGISTRATION_EMAIL_DOMAIN_IS_DIFFERENT",
  AUTH_ACCOUNT_DISABLED = "AUTH_ACCOUNT_DISABLED",
  AUTH_ACCOUNT_NOT_CONFIRMED = "AUTH_ACCOUNT_NOT_CONFIRMED",
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_INVALID_REFRESH_TOKEN = "AUTH_INVALID_REFRESH_TOKEN",
  ACTIVATION_ACCOUNT_NOT_FOUND = "ACTIVATION_ACCOUNT_NOT_FOUND",
  ACTIVATION_ACCOUNT_ACTIVATED = "ACTIVATION_ACCOUNT_ACTIVATED",
  ENTER_REGISTERED_EMAIL = "ENTER_REGISTERED_EMAIL",
  INVALID_VERIFICATION_KEY = "INVALID_VERIFICATION_KEY",
  INVALID_RESET_PWD_KEY = "INVALID_RESET_PWD_KEY",
  SUBMIT_IN_REVIEW = "SUBMIT_IN_REVIEW",
  SUBMIT_DATASET_NOT_FOUND = "SUBMIT_DATASET_NOT_FOUND",
  MESSAGE_CANNOT_SENT = "MESSAGE_CANNOT_SENT",
  SUPPLIER_EXIST_BY_YEAR = "SUPPLIER_EXIST_BY_YEAR",
}

export const ExceptionMessage = {
  USER_NOT_FOUND: "Cannot find user",
  SIMILAR_PASSWORD: "The password you have entered has been used previously, please enter a new password.",
  PASSWORDS_DO_NOT_MATCH: "Confirm password does not match",
  PASSWORDS_DO_NOT_MATCH_REGEX: "Ensure that the “Your password must contain” message that is in the Security Policy requirements message is displayed.",
  REGISTRATION_EMAIL_EXISTS: "A user with this e-mail already exists, please try one of the following options: log-in with existing account, reset your password or create an account with a different e-mail.",
  REGISTRATION_EMAIL_DOMAIN_IS_DIFFERENT: "Email domain is different from the company domain selected for joining",
  AUTH_ACCOUNT_DISABLED: `Your account has been disabled, please contact ${process.env.REACT_APP_TECH_SUPPORT_EMAIL || ""}`,
  AUTH_ACCOUNT_NOT_CONFIRMED: "Your account has not been activated, please check your e-mail including your spam folder and follow the link to activate your account.",
  AUTH_INVALID_CREDENTIALS: "The email and password combination you have entered are not valid. Please try again or recover your account using the forgot password link.",
  AUTH_INVALID_REFRESH_TOKEN: "Invalid refresh token",
  ACTIVATION_ACCOUNT_NOT_FOUND: "Account not found",
  ACTIVATION_ACCOUNT_ACTIVATED: "Account already activated",
  ENTER_REGISTERED_EMAIL: "There is no account found with this e-mail. Please enter a registered user email or sign up to create a new account.",
  INVALID_VERIFICATION_KEY: "Verification key is invalid",
  INVALID_RESET_PWD_KEY: "This link can only be used once. Please go to Forgot password to regenerate a new link to change your password",
  SUBMIT_IN_REVIEW: "Data set is in review",
  SUBMIT_DATASET_NOT_FOUND: "Last data set not found",
  MESSAGE_CANNOT_SENT: "Message wasn't sent",
  SUPPLIER_EXIST_BY_YEAR: "Supplier can't be added multiple times in the supply chain for the same period",
}
