export enum STATUS {
  AVAILABLE = "AVAILABLE",
  ONBOARD_ME = "ONBOARD_ME",
  PENDING = "PENDING",
  PARTIAL = "PARTIAL",
  INCOMPLETE = "INCOMPLETE",
  COMPLETE = "COMPLETE",
  INVITE_ME = "INVITE_ME",
  INVITED = "INVITED",
}

export const MULTIPLE = "Multiple";
