export const fieldsConfig = {
  generalBackground: {
    companyName: "Company Name",
    companyDescription: "About Your Company",
    city: "City",
    country: "Country",
    stockExchangeListed: "Listed",
    homeStockExchangeId: "Home Stock Exchange",
    industrySectorId: "Industry",
    industrySubsectorId: "Sub-Sector",
  },
  financialInformation: {
    isFinancialYear: "Reporting Year",
    startMonth: "Financial Year Start Month",
    baseCurrencyId: "Base Currency",
    yearRepresentationId: "Year",
    revenue: "Revenue",
    netProfit: "Net Profit",
  },
  ghgInventoryMethod: {
    emissionsInventoryMethodId: "Emissions Accounting Method",
    otherEmissionsInventoryMethod: "Custom Emissions Accounting Method",
    organisationalBoundaryId: "Organisational Boundary",
    organisationalBoundaryCriteriaId: "Approach Criteria",
    auditingValidationId: "Auditing and Validation",
    auditingValidationOther: "Auditing and Validation",
  },
  inventoryEmissions: {
    scope1: "Scope 1",
    scope2: "Scope 2",
    scope3: "Scope 3",
    yearRepresentationId: "Year",
    isFinancialYear: "Reporting Year",
    financialYearStartMonth: "Financial Year Start Month",
    sourceValue: "Emission Source",
    sourceValue1: "Fuel Use- Mobile Combustion",
    sourceValue2: "Fuel Use- Stationary Combustion",
    sourceValue3: "Other Process Emissions",
    sourceValue4: "Fugitive Emissions: Refrigerants and Aerosols",
    sourceValue5: "Fugitive Emissions: Waste",
    sourceValue6: "Fugitive Emissions: Land Use",
    sourceValue7: "Fugitive Emissions: Other",
    sourceValue8: "Purchased Electricity",
    sourceValue9: "Purchased Heat, Cooling and Steam",
    sourceValue10: "Purchased Goods and Services",
    sourceValue11: "Capital Goods",
    sourceValue12: "Fuels and Energy Use",
    sourceValue13: "Upstream Transportation and Distribution",
    sourceValue14: "Waste generated in operations",
    sourceValue15: "Business travel",
    sourceValue16: "Employee commuting",
    sourceValue17: "Upstream leased assets",
    sourceValue18: "Downstream Transportation and Distribution",
    sourceValue19: "Processing of sold products",
    sourceValue20: "Use of sold products",
    sourceValue21: "End-of-life treatment of sold products",
    sourceValue22: "Downstream leased assets",
    sourceValue23: "Franchises",
    sourceValue24: "Investments",
    carbonCreditCategoryId: "Participation of Carbon Credits",
    quantity: "Quantity",
    cost: "Cost",
    certificationBody: "Certification Body",
    dataSetGhgInventoryMethodOperationalBoundaries:
      "Organisational Boundary Checklist",
  },
  ghgTargetSetting: {
    scope1: "Baseline / Scope 1",
    scope2: "Baseline / Scope 2",
    scope3: "Baseline / Scope 3",
    yearRepresentationId: "Baseline / Year",
    isFinancialYear: "Baseline / Baseline Year",
    financialYearStartMonth: "Baseline / Financial Year Start Month",
    emissionsReductionTargetScopeId: "GHG Reduction Targets / Scope",
    targetTypeId: "GHG Reduction Targets / Type",
    targetReductionPercentage: "GHG Reduction Targets / Reduction",
    targetYear: "GHG Reduction Targets / Year",
    targetReductionShortTermPlan1: "Short Term Reduction / Target Year 2022",
    targetReductionShortTermPlan2: "Short Term Reduction / Target Year 2023",
    targetReductionShortTermPlan3: "Short Term Reduction / Target Year 2024",
    targetReductionShortTermPlan4: "Short Term Reduction / Target Year 2025",
  },
  climateMetrics: {
    baseCurrencyId: "Carbon Price Currency",
    carbonPriceCoverageId: "Operational Coverage",
    carbonPriceCoverageTypeId: "Operational Coverage Type",
    carbonPrice: "Carbon Price",
    climateMechanismsInfluenceMetrics: "Climate Influence",
  },
  supportingDocuments: {},
};
