export const IMPACT_PRODUCT_NAME = "IMPACT";
export const TRACE_PRODUCT_NAME = "TRACE";

export const TRACE_XS_VARIANT_NAME = "TRACE XS";
export const TRACE_S_VARIANT_NAME = "TRACE S";
export const TRACE_M_VARIANT_NAME = "TRACE M";
export const TRACE_L_VARIANT_NAME = "TRACE L";
export const TRACE_UNLIMITED_VARIANT_NAME = "TRACE UNLIMITED";

export const IMPACT_PERFORMANCE_VARIANT_NAME = "IMPACT PERFORMANCE";
export const IMPACT_MEASUREMENT_VARIANT_NAME = "IMPACT MEASUREMENT";
export const IMPACT_PERFORMANCE_MEASUREMENT_VARIANT_NAME =
  "IMPACT PERFORMANCE+MEASUREMENT";
